// Auto-generated by scripts/generate_vehicle_catalog_ts.py. Do not edit manually.

import type { ConstantCatalog } from '../types/tco.types';

export const CONSTANTS: ConstantCatalog = {
  "ART_ANNUAL_KMS": 84000,
  "BATTERY_DEGRADATION_RATE": 0.025,
  "BATTERY_LIFE_VARIATION_BASE": 2.0,
  "BATTERY_RECYCLE_VALUE": 13,
  "BATTERY_REPLACEMENT_COST": 130,
  "BATTERY_USABLE_RANGE_FACTOR": 0.6,
  "CHARGER_COST": 300000,
  "CHARGING_MIX_PROPORTIONS": {
    "BEV": {
      "Articulated": {
        "offpeak": 0.33,
        "public": 0.57,
        "retail": 0.0,
        "solar": 0.0
      },
      "Light Rigid": {
        "offpeak": 0.86,
        "public": 0.14,
        "retail": 0.0,
        "solar": 0.0
      },
      "Medium Rigid": {
        "offpeak": 0.86,
        "public": 0.14,
        "retail": 0.0,
        "solar": 0.0
      }
    }
  },
  "CHARGING_TIME_HOURS": {
    "Articulated": 1.0,
    "Light Rigid": 0.6,
    "Medium Rigid": 0.75
  },
  "DAYS_IN_YEAR": 365,
  "DEPRECIATION_RATE_FIRST_YEAR": 0.2,
  "DEPRECIATION_RATE_ONGOING": 0.1,
  "DIESEL_EMISSIONS": 2.68,
  "DIESEL_PRICE": 2.05,
  "DISCOUNT_RATE": 0.05,
  "DOWN_PAYMENT_RATE": 0.2,
  "FINANCING_TERM": 5,
  "FREIGHT_RATE_PER_TONNE_KM": {
    "Articulated": 0.08,
    "Light Rigid": 0.25,
    "Medium Rigid": 0.25
  },
  "FUEL_TAX_CREDIT": 0.203,
  "GRID_UPGRADE": 1000000,
  "HOURLY_WAGE": 47,
  "HOURS_IN_YEAR": 8760,
  "INFLATION_RATE": 0.025,
  "INFRASTRUCTURE_LIFE": 15,
  "INSURANCE_RATE_BEV": 0.035,
  "INSURANCE_RATE_DSL": 0.0315,
  "INTEREST_RATE": 0.06,
  "MAINTENANCE_COST_PER_KM": {
    "BEV": {
      "Articulated": 0.19,
      "Light Rigid": 0.1,
      "Medium Rigid": 0.1
    },
    "Diesel": {
      "Articulated": 0.28,
      "Light Rigid": 0.18,
      "Medium Rigid": 0.18
    }
  },
  "MONTHS_IN_YEAR": 12,
  "OFFPEAK_CHARGING_EMISSIONS": 0.7,
  "OFFPEAK_CHARGING_PRICE": 0.15,
  "OTHER_INSURANCE": 2000,
  "PAYLOAD_UTILISATION_FACTOR": {
    "Articulated": 0.9,
    "Light Rigid": 0.8,
    "Medium Rigid": 0.8
  },
  "PUBLIC_CHARGING_EMISSIONS": 0.7,
  "PUBLIC_CHARGING_PRICE": 0.5,
  "RETAIL_CHARGING_EMISSIONS": 0.7,
  "RETAIL_CHARGING_PRICE": 0.3,
  "RIGID_ANNUAL_KMS": 23000,
  "ROAD_USER_CHARGE": 0.305,
  "SOLAR_CHARGING_EMISSIONS": 0.04,
  "SOLAR_CHARGING_PRICE": 0.04,
  "SOLAR_MAINTENANCE": 0.15,
  "SOLAR_PANEL_INSTALLATION": 1285,
  "STAMP_DUTY_RATE": 0.03,
  "STORAGE_INSTALLATION": 423,
  "STORAGE_MAINTENANCE": 0.025,
  "VEHICLE_LIFE": 15,
  "WEEKS_IN_YEAR": 52,
  "WORKING_DAYS": 255
} as const;

