// Auto-generated by scripts/generate_vehicle_catalog_ts.py. Do not edit manually.

import type { PolicyCatalog } from '../types/tco.types';

export const POLICY_CONFIG: PolicyCatalog = {
  "carbon_price": {
    "description": "Price on carbon emissions from diesel vehicles",
    "enabled": false,
    "name": "Carbon Pricing",
    "policy_type": "CarbonPrice",
    "price_per_tonne": 0
  },
  "charging_grant": {
    "description": "Grant for charging infrastructure installation",
    "enabled": false,
    "grant_percentage": 0.0,
    "max_amount": null,
    "name": "Charging Infrastructure Grant",
    "policy_type": "ChargingInfrastructureGrant"
  },
  "green_loan_subsidy": {
    "description": "Reduced interest rate for BEV financing",
    "enabled": false,
    "name": "Green Loan Subsidy",
    "policy_type": "GreenLoanSubsidy",
    "rate_reduction": 0.0
  },
  "percentage_rebate": {
    "description": "Percentage-based rebate on BEV purchase price",
    "enabled": false,
    "max_amount": null,
    "name": "Percentage Purchase Rebate",
    "percentage": 0.0,
    "policy_type": "PercentageRebate"
  },
  "purchase_rebate": {
    "amount": 0,
    "description": "Fixed dollar amount rebate for new BEV purchases",
    "enabled": false,
    "name": "Fixed Purchase Rebate",
    "policy_type": "PurchaseRebate"
  },
  "stamp_duty_exemption": {
    "description": "Full or partial exemption from stamp duty for BEVs",
    "enabled": false,
    "exemption_percentage": 0.0,
    "name": "Stamp Duty Exemption",
    "policy_type": "StampDutyExemption"
  }
} as const;

