#!/usr/bin/env python3
"""Generate shared TypeScript payloads (vehicles, constants, scenarios, policies)."""

from __future__ import annotations

from dataclasses import asdict
import hashlib
import json
import keyword
from pathlib import Path
import sys
from typing import Any, Dict, List

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from data import policies  # noqa: E402
import data.constants as const  # noqa: E402
from data.scenarios import SCENARIOS  # noqa: E402
from data.vehicles import ALL_MODELS  # noqa: E402

VEHICLE_OUTPUT = REPO_ROOT / "shared/data/vehicleCatalog.ts"
CONSTANTS_OUTPUT = REPO_ROOT / "shared/data/constants.generated.ts"
SCENARIOS_OUTPUT = REPO_ROOT / "shared/data/scenarios.ts"
POLICIES_OUTPUT = REPO_ROOT / "shared/data/policies.ts"
HEADER = "// Auto-generated by scripts/generate_vehicle_catalog_ts.py. Do not edit manually.\n\n"
SUMMARY_FIELDS = [
    "vehicle_id",
    "model_name",
    "drivetrain_type",
    "weight_class",
    "comparison_pair",
]
DETAIL_FIELDS: List[str] = SUMMARY_FIELDS + [
    "payload",
    "msrp",
    "range_km",
    "battery_capacity_kwh",
    "kwh_per_km",
    "litres_per_km",
    "annual_registration",
    "annual_kms",
]


def build_vehicle_payload() -> list[dict[str, float | str]]:
    payload: list[dict[str, float | str]] = []
    for model in ALL_MODELS:
        data = asdict(model)
        payload.append({field: data[field] for field in DETAIL_FIELDS})
    return payload


def compute_catalog_version(details: list[dict[str, float | str]]) -> str:
    """
    Compute a deterministic version string for the vehicle catalog.

    The version is based on a hash of the serialized vehicle data, ensuring
    any change to vehicle data produces a new version. This enables automatic
    cache invalidation on the frontend.

    Format: v1-<short_hash> (e.g., "v1-a3f2c1")
    """
    # Sort keys for deterministic serialization
    json_str = json.dumps(details, sort_keys=True, separators=(",", ":"))
    hash_digest = hashlib.sha256(json_str.encode()).hexdigest()[:8]
    return f"v1-{hash_digest}"


def build_constants_payload() -> Dict[str, Any]:
    payload: Dict[str, Any] = {}
    for attr in dir(const):
        if not attr.isupper():
            continue
        value = getattr(const, attr)
        try:
            json.dumps(value)
        except TypeError:
            continue
        payload[attr] = value
    return payload


def _format_ts_property_name(name: str) -> str:
    if name.isidentifier() and not keyword.iskeyword(name):
        return name
    return json.dumps(name)


def _render_ts_type(value: Any, indent_level: int = 0) -> str:
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, (int, float)):
        return "number"
    if isinstance(value, str):
        return "string"
    if value is None:
        return "null"
    if isinstance(value, list):
        if not value:
            return "unknown[]"
        item_types = sorted({_render_ts_type(item, indent_level + 1) for item in value})
        if len(item_types) == 1:
            return f"{item_types[0]}[]"
        return f"Array<{' | '.join(item_types)}>"
    if isinstance(value, dict):
        indent = "  " * indent_level
        child_indent = "  " * (indent_level + 1)
        lines = ["{"]
        for key in sorted(value):
            property_name = _format_ts_property_name(str(key))
            property_type = _render_ts_type(value[key], indent_level + 1)
            lines.append(f"{child_indent}{property_name}: {property_type};")
        lines.append(f"{indent}}}")
        return "\n".join(lines)
    return "unknown"


def build_scenarios_payload() -> Dict[str, Dict[str, Any]]:
    scenarios: Dict[str, Dict[str, Any]] = {}
    for key, scenario in SCENARIOS.items():
        data = asdict(scenario)
        data["key"] = key
        scenarios[key] = data
    return scenarios


def build_policies_payload() -> Dict[str, Dict[str, Any]]:
    payload: Dict[str, Dict[str, Any]] = {}
    for key, policy in policies.POLICIES.items():
        data = asdict(policy)
        data["policy_type"] = policy.__class__.__name__
        payload[key] = data
    return payload


def render_vehicle_ts(details: list[dict[str, float | str]], version: str) -> str:
    details_json = json.dumps(details, indent=2, sort_keys=False)
    return (
        f"{HEADER}"
        "import type { VehicleDetail, VehicleSummary } from '../types/tco.types';\n\n"
        "/**\n"
        " * Catalog version - auto-generated from vehicle data hash.\n"
        " * Used for cache invalidation when vehicle data changes.\n"
        " */\n"
        f"export const VEHICLE_CATALOG_VERSION = '{version}';\n\n"
        f"export const VEHICLE_DETAILS: VehicleDetail[] = {details_json} as const;\n\n"
        "export const VEHICLE_BY_ID: Record<string, VehicleDetail> = VEHICLE_DETAILS.reduce(\n"
        "  (acc, vehicle) => {\n"
        "    acc[vehicle.vehicle_id] = vehicle;\n"
        "    return acc;\n"
        "  },\n"
        "  {} as Record<string, VehicleDetail>\n"
        ");\n\n"
        "export const VEHICLE_SUMMARIES: VehicleSummary[] = VEHICLE_DETAILS.map(\n"
        "  ({ vehicle_id, model_name, drivetrain_type, weight_class, comparison_pair }) => ({\n"
        "    vehicle_id,\n"
        "    model_name,\n"
        "    drivetrain_type,\n"
        "    weight_class,\n"
        "    comparison_pair,\n"
        "  })\n"
        ");\n"
    )


def render_constants_ts(constants: Dict[str, Any]) -> str:
    json_blob = json.dumps(constants, indent=2, sort_keys=True)
    constants_schema = _render_ts_type(constants)
    return (
        f"{HEADER}"
        "export interface ConstantsSchema "
        f"{constants_schema}\n\n"
        "export type ConstantCatalog = ConstantsSchema;\n\n"
        f"export const CONSTANTS: ConstantsSchema = {json_blob} as const;\n"
    )


def render_scenarios_ts(scenarios: Dict[str, Dict[str, Any]]) -> str:
    json_blob = json.dumps(scenarios, indent=2, sort_keys=True)
    return (
        f"{HEADER}"
        "import type { ScenarioDefinitionMap } from '../types/tco.types';\n\n"
        f"export const SCENARIO_DEFINITIONS: ScenarioDefinitionMap = {json_blob} as const;\n"
    )


def render_policies_ts(policies_payload: Dict[str, Dict[str, Any]]) -> str:
    json_blob = json.dumps(policies_payload, indent=2, sort_keys=True)
    return (
        f"{HEADER}"
        "import type { PolicyCatalog } from '../types/tco.types';\n\n"
        f"export const POLICY_CONFIG: PolicyCatalog = {json_blob} as const;\n"
    )


def ensure_output_dir() -> None:
    VEHICLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def main() -> None:
    ensure_output_dir()
    details = build_vehicle_payload()
    version = compute_catalog_version(details)
    print(f"Generated vehicle catalog version: {version}")
    VEHICLE_OUTPUT.write_text(
        render_vehicle_ts(details, version) + "\n", encoding="utf-8"
    )
    constants = build_constants_payload()
    CONSTANTS_OUTPUT.write_text(render_constants_ts(constants) + "\n", encoding="utf-8")
    scenarios = build_scenarios_payload()
    SCENARIOS_OUTPUT.write_text(render_scenarios_ts(scenarios) + "\n", encoding="utf-8")
    policy_payload = build_policies_payload()
    POLICIES_OUTPUT.write_text(
        render_policies_ts(policy_payload) + "\n", encoding="utf-8"
    )
    print("Generated files:")
    print(f"  - {_display_path(VEHICLE_OUTPUT)}")
    print(f"  - {_display_path(CONSTANTS_OUTPUT)}")
    print(f"  - {_display_path(SCENARIOS_OUTPUT)}")
    print(f"  - {_display_path(POLICIES_OUTPUT)}")


if __name__ == "__main__":
    main()
